# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1024']
-   repo: local
    hooks:
    -   id: shellcheck
        name: ShellCheck
        entry: shellcheck
        args:
        -   --external-sources
        language: system
        types: [shell]
    -   id: ansible-lint
        name: Ansible Lint
        entry: make
        args:
        -   ansible-lint
        language: system
        types: [yaml]
        pass_filenames: false
