---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    docker_compose_version: 2.0.1
  tasks:
    # https://www.freedesktop.org/software/systemd/man/sd_booted.html
    - name: All - Check if systemd is running
      ansible.builtin.stat:
        path: /run/systemd/system/
      register: stat_run_systemd

    - name: Docker
      tags: [system]
      become: true
      ansible.builtin.import_tasks: tasks/system/docker.yml

    - name: All - Enable docker
      become: true
      ansible.builtin.systemd:
        name: docker.service
        enabled: true
        state: started
        daemon_reload: true
      when:
        - stat_run_systemd.stat.exists
        - stat_run_systemd.stat.isdir
