---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: All - Check if dockerenv exists
      ansible.builtin.stat:
        path: /.dockerenv
      register: file_dockerenv

    - name: Flatpaks
      tags: [user]
      ansible.builtin.import_tasks: tasks/user/flatpaks.yml
