---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    signing_keys:
      razer_fedora:
        "33":
          fingerprint: E96C496E4E77C159C2FCA053062F9FD4D6D11CE4
        "34":
          fingerprint: E96C496E4E77C159C2FCA053062F9FD4D6D11CE4
  tasks:
    - name: All - Check if dockerenv exists
      ansible.builtin.stat:
        path: /.dockerenv
      register: file_dockerenv

    - name: Razer
      tags: [system]
      become: true
      ansible.builtin.import_tasks: tasks/system/razer.yml
