---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    dive_version: 0.9.2
    docker_compose_version: 1.26.2
    signing_keys:
      rpmfusion_free_fedora: # https://rpmfusion.org/keys
        "28":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-28
          fingerprint: 34249D2CB3758B5548E2874FC08D326909EAB3F2
        "29":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-29
          fingerprint: BD127385C312090FF2F35FA11191A7C442F19ED0
        "30":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-30
          fingerprint: 80C3B2C6E727F3E092B473E03DF2CE43C0AEDA6E
        "31":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-31
          fingerprint: 59A7FE07F664C1B27687C5D26DEEF051C481937A
        "32":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-32
          fingerprint: 7BDA98EF593050A34B1697ABA0EE9D83100BCD92
      rpmfusion_nonfree_fedora: # https://rpmfusion.org/keys
        "28":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-28
          fingerprint: 3DE8C682E38EE9BC0FDFEA47FCAE2EA87F858107
        "29":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-29
          fingerprint: 18A50439A072A393E47178D49C009EABD6841AF8
        "30":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-30
          fingerprint: 80171C8D2CC8AAB84C8448E9BDD6ECC41D14A795
        "31":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-31
          fingerprint: 4CAB951A7493D92CADEC04219CE63A0354A86092
        "32":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-32
          fingerprint: FE5A9393CB6E271B5A90CC1B0D9A76996DC1BE18
  tasks:
    - name: debug info
      debug:
        msg: "{{ ansible_facts }}"
      tags: [ never, debug ]

    ### --- System ---
    - name: Repositories
      tags: [ system, dev, repo ]
      become: true
      import_tasks: tasks/system/repositories.yml

    - name: Packages
      tags: [ system, dev, packages ]
      become: true
      import_tasks: tasks/system/packages.yml

    - name: Containers
      tags: [ system, dev, containers]
      become: true
      import_tasks: tasks/system/containers.yml

    - name: Security Settings
      tags: [ system, security ]
      become: true
      import_tasks: tasks/system/security.yml

    ### --- Userspace ---
    # Install dotfiles first so CI can detect drift
    - import_tasks: tasks/user/dotfiles.yml
      tags: [ user, dotfiles ]
    - import_tasks: tasks/user/applications.yml
      tags: [ user, applications ]
    - import_tasks: tasks/user/flatpaks.yml
      tags: [ user, flatpaks ]
    - import_tasks: tasks/user/python.yml
      tags: [ user, python ]
    - import_tasks: tasks/user/rust.yml
      tags: [ user, rust ]
    - import_tasks: tasks/user/ui.yml
      tags: [ user, ui ]
    - import_tasks: tasks/user/ides.yml
      tags: [ user, ides ]
