---
- hosts: localhost
  vars:
    dive_version: 0.9.2
    docker_compose_version: 1.26.2
  tasks:
    - name: debug info
      debug:
        msg: "{{ ansible_facts }}"
      tags: [ never, debug ]

    ### --- System ---
    - name: Repositories
      tags: [ system, dev, repo ]
      become: true
      import_tasks: tasks/system/repositories.yml

    - name: Packages
      tags: [ system, dev, packages ]
      become: true
      import_tasks: tasks/system/packages.yml

    - name: Containers
      tags: [ system, dev, containers]
      become: true
      import_tasks: tasks/system/containers.yml

    - name: Security Settings
      tags: [ system, security ]
      become: true
      import_tasks: tasks/system/security.yml

    ### --- Userspace ---
    # Install dotfiles first so CI can detect drift
    - import_tasks: tasks/user/dotfiles.yml
      tags: [ user, dotfiles ]
    - import_tasks: tasks/user/applications.yml
      tags: [ user, applications ]
    - import_tasks: tasks/user/flatpaks.yml
      tags: [ user, flatpaks ]
    - import_tasks: tasks/user/python.yml
      tags: [ user, python ]
    - import_tasks: tasks/user/rust.yml
      tags: [ user, rust ]
    - import_tasks: tasks/user/ui.yml
      tags: [ user, ui ]
    - import_tasks: tasks/user/ides.yml
      tags: [ user, ides ]
