---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: RedHat - Enable flatpak updates
      systemd:
        name: flatpak-update.timer
        enabled: yes
        state: started
        daemon_reload: yes
        scope: user
      when: ansible_os_family == 'RedHat'

    - name: RedHat - Enable security updates
      become: true
      systemd:
        name: dnf-automatic.timer
        enabled: yes
        state: started
        daemon_reload: yes
      when: ansible_os_family == 'RedHat'

    - name: RedHat - Enable docker
      become: true
      systemd:
        name: docker.service
        enabled: yes
        state: started
        daemon_reload: yes
      when: ansible_os_family == 'RedHat'
