---
- hosts: localhost
  tasks:
    - name: RedHat - Enable security updates
      become: true
      systemd:
        name: dnf-automatic.timer
        enabled: yes
        state: started
        daemon_reload: yes
      when: ansible_os_family == 'RedHat'

    - name: RedHat - Enable docker
      become: true
      systemd:
        name: docker.service
        enabled: yes
        state: started
        daemon_reload: yes
      when: ansible_os_family == 'RedHat'
