---
# https://taskfile.dev

version: "3"

includes:
  ans:
    taskfile: ./playbooks/Taskfile.yaml
    dir: playbooks

tasks:
  default: go-task -a 2>/dev/null || task -a

  setup:
    desc: Run the full setup
    cmds:
      - ./setup.sh
