---
- name: Ubuntu >=18 - Install packages
  apt:
    pkg:
      - 1password
      - flameshot
      - libasound2
    state: present
  when: ansible_distribution_major_version|int >= 18

- name: Ubuntu >=20 - Install packages
  apt:
    pkg:
      - fd-find
      - python3-cairo
      - python3-launchpadlib
      - python3-testresources
      - ripgrep
    state: present
  when: ansible_distribution_major_version|int >= 20
