---
- name: Ubuntu >=18 - Install packages
  ansible.builtin.apt:
    pkg:
      - 1password
      - 1password-cli
      - flameshot
      - npm
      - libasound2
    state: present
  when: ansible_distribution_major_version | int >= 18

- name: Ubuntu >=20 - Install packages
  ansible.builtin.apt:
    pkg:
      - python3-cairo
      - python3-launchpadlib
      - python3-testresources
    state: present
  when: ansible_distribution_major_version | int >= 20

- name: Ubuntu >=22 - Install packages
  ansible.builtin.apt:
    pkg:
      - podman
    state: present
  when: ansible_distribution_major_version | int >= 22
