---
  - name: Archlinux - Install packages
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - bash
      - bash-completion
      - code
      - curl
      - docker
      - exa
      - fd
      - flameshot
      - flatpak
      - gcc
      - gdb
      - gzip
      - jq
      - keybase
      - keybase-gui
      - lynis # Security scanning tool
      - make
      - nodejs
      - npm
      - python-psutil
      - shellcheck
      - tk # windowing toolkit needed for gitk
      - tree
      - wget
      - xz
      - zsh
