---
- name: Archlinux - Install packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  retries: 5
  delay: 5
  loop:
    - bash
    - bash-completion
    - bat  # rust version of cat
    - code
    - curl
    - exa
    - fd
    - flameshot
    - flatpak
    - gcc
    - gdb
    - git-delta  # Syntax-highlighting pager for git
    - gzip
    - hyperfine  # CLI benchmarking
    - jq
    - keybase
    - keybase-gui
    - kubectl
    - lynis  # Security scanning tool
    - make
    - nodejs
    - npm
    - podman
    - python-psutil
    - ripgrep
    - shellcheck
    - starship  # CLI prompt
    - tk  # windowing toolkit needed for gitk
    - tree
    - wget
    - xz
    - zsh

- name: Archlinux - Best effort to install optional packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - dconf-editor
    - neofetch
  failed_when: false
