---
### --- Family Specific Setup
- name: Archlinux GCloud
  ansible.builtin.import_tasks: archlinux/gcloud.yml
  when: ansible_os_family == 'Archlinux'

- name: Debian GCloud
  ansible.builtin.import_tasks: debian/gcloud.yml
  when: ansible_os_family == 'Debian'

- name: RedHat GCloud
  ansible.builtin.import_tasks: redhat/gcloud.yml
  when: ansible_os_family == 'RedHat'
