---
- name: Fedora - Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: fedora_install_packages
  until: fedora_install_packages is succeeded
  loop:
    - community-mysql-devel  # from fedora modular
    - dbus-daemon
    - dbus-tools
    - fd-find
    - flameshot
    - fzf
    - gdouros-symbola-fonts
    - google-noto-sans-display-fonts
    - google-noto-sans-display-vf-fonts
    - google-noto-sans-mono-fonts
    - google-noto-sans-mono-vf-fonts
    - google-noto-sans-vf-fonts
    - google-roboto-mono-fonts
    - hyperfine  # CLI benchmarking
    - intel-media-driver
    - kubernetes-client  # kubectl
    - levien-inconsolata-fonts
    - mozilla-fira-fonts-common
    - mozilla-fira-mono-fonts
    - mozilla-fira-sans-fonts
    - open-policy-agent
    # TODO: move this to redhat when centos gets support
    - podman-compose  # emulate docker-compose
    - python3-psutil
    - ShellCheck
    - sqlitebrowser
    - texlive-montserrat
    - yubikey-manager
