---
- name: CentOS - Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  retries: 5
  delay: 5
  loop:
    - dbus-daemon
    - kubectl

- name: CentOS - Install stream8 packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python39-psutil
  when:
    - ansible_distribution_major_version|int <= 8

- name: CentOS - Install stream9 packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3-psutil
  when:
    - ansible_distribution_major_version|int >= 9
