---
- name: RedHat - Add dnf plugins
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core

- name: RedHat - Import 1Password signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc
    fingerprint: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  register: rpm_key_1password

- name: RedHat - Add 1Password beta repository
  ansible.builtin.yum_repository:
    file: 1password-ansible
    name: 1password-beta
    description: 1Password - Beta
    baseurl: https://downloads.1password.com/linux/rpm/beta/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    repo_gpgcheck: true

- name: RedHat - Add 1Password stable repository
  ansible.builtin.yum_repository:
    file: 1password-ansible
    name: 1password-stable
    description: 1Password - Stable
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    repo_gpgcheck: true

# TODO: remove this workaround when dnf uses the rpm key database
- name: RedHat - refresh dnf keys for 1Password  # noqa no-handler
  ansible.builtin.command: >
    dnf -q makecache -y --disablerepo='*'
    --enablerepo='1password-beta' --enablerepo='1password-stable'
  when: rpm_key_1password.changed

- name: RedHat - Import Keybase signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://keybase.io/docs/server_security/code_signing_key.asc
    fingerprint: 222B85B0F90BE2D24CFEB93F47484E50656D16C7
  register: rpm_key_keybase
  ignore_errors: true

- name: RedHat - Add Keybase repository
  ansible.builtin.yum_repository:
    file: keybase
    name: keybase
    description: keybase
    baseurl: http://prerelease.keybase.io/rpm/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
    metadata_expire: '60'
    # This repo was previously signed with the key but they no longer sign the
    # repo when publishing new releases. This causes a bad signature.
    repo_gpgcheck: false
  when: rpm_key_keybase is succeeded

# TODO: remove this workaround when dnf uses the rpm key database
- name: RedHat - refresh dnf keys for Keybase  # noqa no-handler
  ansible.builtin.command: "dnf -q makecache -y --disablerepo='*' --enablerepo='keybase'"
  when:
    - rpm_key_keybase is succeeded
    - rpm_key_keybase.changed

- name: RedHat - Import VSCode signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
    fingerprint: BC528686B50D79E339D3721CEB3E94ADBE1229CF
  register: rpm_key_microsoft

- name: RedHat - Add VSCode repository
  ansible.builtin.yum_repository:
    file: vscode
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    repo_gpgcheck: true

# TODO: remove this workaround when dnf uses the rpm key database
- name: RedHat - refresh dnf keys for VSCode  # noqa no-handler
  ansible.builtin.command: "dnf -q makecache -y --disablerepo='*' --enablerepo='code'"
  when: rpm_key_microsoft.changed

- name: RedHat - Import Zoom signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://zoom.us/linux/download/pubkey?version=5-12-6
    fingerprint: 59C86188E22ABB19BD5540477B04A1B8DD79B481
  register: rpm_key_zoom
  # Zoom is an optional package and CentOS:stream9 does not like this key
  failed_when: false

- name: RedHat - check if rpmfusion-free.repo file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: rpmfusion_free_repo

- name: RedHat - check if rpmfusion-free-updates.repo file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-free-updates.repo
  register: rpmfusion_free_updates_repo

- name: RedHat - check if rpmfusion-nonfree.repo file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree.repo
  register: rpmfusion_nonfree_repo

- name: RedHat - check if rpmfusion-nonfree-updates.repo file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
  register: rpmfusion_nonfree_updates_repo

# Install of dependencies is specific to the os family
- name: RedHat - update zoom-yum-repo  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://gitlab.com/perobertson/zoom-yum-repo.git
    dest: /opt/zoom-yum-repo
  register: git_zoom_yum_repo

### --- Distro specific ---

- name: CentOS Repositories
  ansible.builtin.import_tasks: system_redhat_centos_repositories.yml
  when: ansible_distribution == 'CentOS'

- name: Fedora Repositories
  ansible.builtin.import_tasks: system_redhat_fedora_repositories.yml
  when: ansible_distribution == 'Fedora'
