---
- name: All - create systemd directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc
    - /etc/systemd
    - /etc/systemd/system
    - /etc/systemd/user

- name: All - configure systemd units
  diff: true
  ansible.builtin.copy:
    src: "files{{ item }}"
    dest: "{{ item }}"
    mode: '0644'
  loop:
    - /etc/systemd/user/user-updates.service
    - /etc/systemd/user/user-updates.timer
