---
- name: RedHat - rpm keys for Google
  ansible.builtin.import_tasks: redhat/rpm_keys_google.yml

- name: RedHat - Import google-cloud-cli repository key - 1
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64/repodata/repomd.xml.key
    fingerprint: A362B822F6DEDC652817EA46B53DC80D13EDEF05
  register: import_glcoud_repository_key1

- name: RedHat - Import google-cloud-cli repository key - 2
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64/repodata/repomd.xml.key
    fingerprint: 7F92E05B31093BEF5A3C2D38FEEA9169307EA071
  register: import_glcoud_repository_key2

- name: RedHat - Add Google Cloud SDK repository
  ansible.builtin.yum_repository:
    file: google-cloud-cli
    name: google-cloud-cli
    description: Google Cloud CLI
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      # Repository metadata keys
      - https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64/repodata/repomd.xml.key
      # Old repository metadata key
      # - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      # Package key
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  register: gcloud_repository

# TODO: remove this workaround when dnf uses the rpm key database
- name: RedHat - refresh dnf keys for google-cloud-cli  # noqa no-handler
  ansible.builtin.command: "dnf -q makecache -y --disablerepo='*' --enablerepo='google-cloud-cli'"
  when: >
    gcloud_repository.changed
    or import_glcoud_package_key.changed
    or import_glcoud_repository_key1.changed
    or import_glcoud_repository_key2.changed

- name: RedHat - Best effort to install gcloud
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - google-cloud-cli
  # this passes on centos:stream8 which uses rpm 4.14.3
  # this is failing on centos:stream9 which uses rpm 4.16.1.3
  # this passes on fedora:36 which uses rpm 4.17
  # the error is
  # google-cloud-cli-391.0.0-1.x86_64.rpm
  # Header V4 RSA/SHA1 Signature, key ID 3e1ba8d5: BAD
  # not an rpm package (or package manifest)
  failed_when: false
