---
- name: CentOS - Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: centos_install_packages
  until: centos_install_packages is succeeded
  loop:
    - dbus-daemon
    - kubectl
    - python3-psutil
