---
- name: Debian - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: debian_install_packages
  until: debian_install_packages is succeeded
  loop:
    - bash
    - bash-completion
    - clang  # Front-end for the LLVM compiler
    - cmake  # Needed for installing some rust crates
    - dconf-cli
    - ffmpeg  # Improves video playback
    - flatpak
    - fonts-symbola
    - gdb
    - git
    - gitk
    - htop
    - jq
    - lynis  # Security scanning tool
    - mold  # Faster linker for compiling
    - nodejs
    - npm
    - pkg-config
    - podman
    - python3-dbus
    - python3-psutil
    - seahorse  # key management
    - shellcheck
    - sqlitebrowser
    - sysstat  # iostat
    - tree
    - unzip
    - wget
    - zsh
    - zstd  # Zstandard - Fast real-time compression algorithm

- name: Debian - Install non WSL packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - 1password
    - 1password-cli
    - code  # VSCode
  when: not running_in_wsl

- name: Debian - Best effort to install optional packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - dconf-editor
    - fd-find
    - neofetch
    - ripgrep
  failed_when: false

- name: Debian - Best effort to install remote packages
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.deb
  failed_when: false

### --- Distro specific ---

- name: Ubuntu Packages
  ansible.builtin.import_tasks: system_debian_ubuntu_packages.yml
  when: ansible_distribution == 'Ubuntu'
