---
- name: Archlinux - Install packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: archlinux_install_packages
  until: archlinux_install_packages is succeeded
  loop:
    - aws-vault
    - bash
    - bash-completion
    - cmake  # Needed for installing some rust crates
    - curl
    - fd
    - ffmpeg  # Improves video playback
    - flameshot
    - flatpak
    - gcc
    - gdb
    - gzip
    - hyperfine  # CLI benchmarking
    - jq
    - keybase
    - keybase-gui
    - kubectl
    - lynis  # Security scanning tool
    - make
    - nodejs
    - npm
    # Used when compiling rust tools
    - pkgconf  # Helper for configuring compiler and linker flags
    - podman
    - podman-compose  # emulate docker-compose
    - podman-docker  # emulate docker
    - python-psutil
    - ripgrep
    # rust provides cargo, cargo-clippy, debuggers, language server, etc.
    # this is different than RedHat which split those components up
    - rust
    - rust-analyzer  # Rust Language Server for IDE integration
    - rust-src  # Rust systems programming language - source code
    - shellcheck
    - tk  # windowing toolkit needed for gitk
    - tree
    - unzip
    - webp-pixbuf-loader  # Allows for viewing of webp images
    - wget
    - xz
    - zsh
    - zstd  # Zstandard - Fast real-time compression algorithm

- name: Archlinux - Install non WSL packages
  community.general.pacman:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: archlinux_install_non_wsl_packages
  until: archlinux_install_non_wsl_packages is succeeded
  loop:
    - code  # VSCode
  when: not running_in_wsl

- name: Archlinux - Best effort to install optional packages
  community.general.pacman:
    pkg: "{{ item }}"
    state: present
  loop:
    - dconf-editor
    - neofetch
  failed_when: false
