---
- name: Debian Repositories
  ansible.builtin.import_tasks: system_debian_repositories.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Repositories
  ansible.builtin.import_tasks: system_redhat_repositories.yml
  when: ansible_os_family == 'RedHat'
