---
### --- Family Specific Packages
- name: Archlinux Packages
  ansible.builtin.import_tasks: archlinux/packages.yml
  when: ansible_os_family == 'Archlinux'

- name: Debian Packages
  ansible.builtin.import_tasks: debian/packages.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Packages
  ansible.builtin.import_tasks: redhat/packages.yml
  when: ansible_os_family == 'RedHat'

### --- Settings that require packages to be installed first

- name: All - Set default shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: All - Install aws-vault
  ansible.builtin.get_url:
    checksum: sha256:https://github.com/99designs/aws-vault/releases/download/v{{ aws_vault_version }}/SHA256SUMS
    dest: /usr/local/bin/aws-vault
    group: root
    owner: root
    url: https://github.com/99designs/aws-vault/releases/download/v{{ aws_vault_version }}/aws-vault-linux-amd64
    mode: "0755"
  # Arch is the only platform which has a package
  # It also comes with docs and completions
  when: ansible_os_family != 'Archlinux'

- name: All - Install custom scripts
  tags: [systemd]
  ansible.builtin.copy:
    src: files/usr/local/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
  loop:
    - create-bootable-usb.bash
    - non-metered-connection.bash
