---
- name: Ubuntu - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: ubuntu_install_packages
  until: ubuntu_install_packages is succeeded
  loop:
    - flameshot
    - npm
    - podman
    - podman-docker  # emulate docker
