---
- name: Ubuntu - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: ubuntu_install_packages
  until: ubuntu_install_packages is succeeded
  loop:
    - flameshot
    - npm
    - podman-docker  # emulate docker

# EOL: 2025-04
- name: Ubuntu >=20 - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: ubuntu20_install_packages
  until: ubuntu20_install_packages is succeeded
  when: ansible_distribution_major_version | int >= 20
  loop:
    - python3-cairo
    - python3-launchpadlib
    - python3-testresources

# EOL: 2027-06
- name: Ubuntu >=22 - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: ubuntu22_install_packages
  until: ubuntu22_install_packages is succeeded
  when: ansible_distribution_major_version | int >= 22
  loop:
    - podman
