# Debian EOL dates https://wiki.debian.org/DebianReleases/
---
- name: Debian - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: debian_debian_install_packages
  until: debian_debian_install_packages is succeeded
  when: ansible_distribution_major_version | int >= 10
  loop: []
