---
- name: All - Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: All - Create user systemd directories
  ansible.builtin.file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - .config/systemd
    - .config/systemd/user

- name: All - Install flatpaks
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop:
    - com.discordapp.Discord
    - com.slack.Slack
    - com.spotify.Client
    - org.videolan.VLC
  retries: 3
  delay: 5
  register: flatpak_install
  until: flatpak_install is succeeded
  when:
    - stat_run_systemd.stat.exists
    - stat_run_systemd.stat.isdir
