---
# Needed for user systemd scripts
- name: All - Create ~/bin
  tags: [systemd]
  ansible.builtin.file:
    path: $HOME/bin
    state: directory
    mode: "0700"

- name: All - Populate ~/bin
  diff: true
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/home/user/bin/{{ item }}"
    dest: "$HOME/bin/{{ item }}"
    state: link
  loop:
    - README.md
    - aws_iam_to_ses.py
    - install-aws.bash
    - install-nvidia.bash

# For user systemd
# https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory
- name: All - Create ~/.local/bin
  tags: [systemd]
  ansible.builtin.file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - .local/bin
    - .local/lib

# This is for the side effect of checking if a default toolchain is set
- name: All - check cargo version
  tags: [systemd]
  ansible.builtin.command:
    cmd: cargo --version
  register: cargo_version
  ignore_errors: true
  changed_when: false

- name: All - rustup set default toolchain
  tags: [systemd]
  ansible.builtin.command:
    cmd: rustup default stable
  when: "'rustup default stable' in cargo_version.stderr"

# There is no option to install from a git source
# https://docs.ansible.com/ansible/latest/collections/community/general/cargo_module.html
- name: All - user-updates
  tags: [systemd]
  ansible.builtin.command:
    cmd: cargo install --git https://gitlab.com/perobertson/user-updates.git
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/user-updates"
  environment:
    CARGO_INSTALL_ROOT: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local"
