---
- name: All - Create user systemd directories
  ansible.builtin.file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - .config/systemd
    - .config/systemd/user

- name: All - Create user services
  diff: true
  ansible.builtin.copy:
    src: "files/home/user/.config/systemd/user/{{ item.name }}"
    dest: "$HOME/.config/systemd/user/{{ item.name }}"
    mode: "0600"
  loop:
    - name: logout-podman-stop.service

# These need to be templated because the path to the files are in the users home
# When the services are enabled they run at boot which is before user shell
# customizations happen.
# Searched directories include /usr/local/bin/, /usr/bin/, /bin/
# and their sbin/ counterparts
- name: All - Create user templated services
  diff: true
  ansible.builtin.template:
    src: "files/home/user/.config/systemd/user/{{ item.name }}.j2"
    dest: "$HOME/.config/systemd/user/{{ item.name }}"
    mode: "0600"
  loop:
    - name: pkenv-update.service
    - name: pyenv-update.service
    - name: rust-tools-update.service
    - name: tfenv-update.service

- name: All - Enable user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
    scope: user
  when:
    - stat_run_systemd.stat.exists
    - stat_run_systemd.stat.isdir
  loop:
    - logout-podman-stop.service
    - pkenv-update.service
    - pyenv-update.service
    - rust-tools-update.service
    - tfenv-update.service
  # TODO: figure out how to get `systemd --user` running
  # Failed to connect to bus: No such file or directory
  failed_when: false
