---
- name: Archlinux - Install packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: archlinux_install_packages
  until: archlinux_install_packages is succeeded
  loop:
    - aws-vault
    - bash
    - bash-completion
    - curl
    - fd
    - ffmpeg  # Improves video playback
    - flameshot
    - flatpak
    - gcc
    - gdb
    - git-delta  # Syntax-highlighting pager for git
    - gzip
    - hyperfine  # CLI benchmarking
    - jq
    - keybase
    - keybase-gui
    - kubectl
    - lynis  # Security scanning tool
    - make
    - nodejs
    - npm
    - podman
    - podman-compose  # emulate docker-compose
    - podman-docker  # emulate docker
    - python-psutil
    - ripgrep
    - shellcheck
    - tk  # windowing toolkit needed for gitk
    - tree
    - unzip
    - webp-pixbuf-loader  # Allows for viewing of webp images
    - wget
    - xz
    - yubikey-manager
    - zsh

- name: Archlinux - Install non WSL packages
  ansible.builtin.pacman:
    pkg: "{{ item }}"
    state: present
  loop:
    - code  # VSCode
  when: not running_in_wsl

- name: Archlinux - Best effort to install optional packages
  ansible.builtin.pacman:
    pkg: "{{ item }}"
    state: present
  loop:
    - dconf-editor
    - neofetch
  failed_when: false
