---
- name: All - Install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube

- name: All - Enable execue for minikube
  file:
    path: /usr/local/bin/minikube
    mode: +x

- name: All - Install docker-compose {{ docker_compose_version }}
  tags: [ docker ]
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: /usr/local/bin/docker-compose-{{ docker_compose_version }}
    mode: '0755'

- name: Non-Debian - Install docker-compose completions {{ docker_compose_version }}
  tags: [ docker ]
  get_url:
    url: "https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/zsh/_docker-compose"
    dest: /usr/share/zsh/site-functions/_docker-compose
    mode: '0644'
  when: ansible_os_family != 'Debian'

- name: Debian - Install docker-compose completions {{ docker_compose_version }}
  tags: [ docker ]
  get_url:
    url: "https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/zsh/_docker-compose"
    dest: /usr/local/share/zsh/site-functions/_docker-compose
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: All - Update link to latest docker-compose
  tags: [ docker ]
  file:
    src: /usr/local/bin/docker-compose-{{ docker_compose_version }}
    dest: /usr/local/bin/docker-compose
    state: hard
    force: yes
    mode: '0755'

- name: All - Enable execue for docker-compose
  tags: [ docker ]
  file:
    src: /usr/local/bin/docker-compose-{{ docker_compose_version }}
    dest: /usr/local/bin/docker-compose
    mode: +rx

- name: All - Add user to docker group
  tags: [ docker ]
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: docker

- name: CentOS - Add user to docker group
  tags: [ docker ]
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: docker
  ignore_errors: "{{ uri_docker_repo_rpm is failed }}"
