---
- name: All - Create docker cli plugins dir
  ansible.builtin.file:
    path: "/usr/local/lib/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - docker
    - docker/cli-plugins

- name: All - Install docker compose {{ docker_compose_version }}
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_machine }}"
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    checksum: "sha256:https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_machine }}.sha256"
    mode: '0755'

- name: All - Enable execue for docker compose
  ansible.builtin.file:
    path: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: +rx

### --- Family Specific Setup
- name: Archlinux Docker
  ansible.builtin.import_tasks: archlinux/docker.yml
  when: ansible_os_family == 'Archlinux'

- name: Debian Docker
  ansible.builtin.import_tasks: debian/docker.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Docker
  ansible.builtin.import_tasks: redhat/docker.yml
  when: ansible_os_family == 'RedHat'

### --- Post actions
- name: All - Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups: docker
