---
- name: All - Install minikube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube

- name: All - Enable execue for minikube
  ansible.builtin.file:
    path: /usr/local/bin/minikube
    mode: +x

### --- Family Specific Setup
- name: Archlinux Kubernetes
  ansible.builtin.import_tasks: archlinux/kubernetes.yml
  when: ansible_os_family == 'Archlinux'

- name: Debian Kubernetes
  ansible.builtin.import_tasks: debian/kubernetes.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Kubernetes
  ansible.builtin.import_tasks: redhat/kubernetes.yml
  when: ansible_os_family == 'RedHat'
