---
### --- Family Specific Packages
- name: Archlinux Packages
  import_tasks: archlinux/packages.yml
  when: ansible_os_family == 'Archlinux'

- name: Debian Packages
  import_tasks: debian/packages.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Packages
  import_tasks: redhat/packages.yml
  when: ansible_os_family == 'RedHat'
