---
- name: Debian Repositories
  import_tasks: debian/repositories.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Repositories
  import_tasks: redhat/repositories.yml
  when: ansible_os_family == 'RedHat'
