---
- name: Debian - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 5
  delay: 5
  loop:
    - 1password
    - 1password-cli
    - bash
    - bash-completion
    - bat  # rust version of cat
    - crudini
    - dconf-cli
    - ffmpeg  # Improves video playback
    - flatpak
    - fonts-symbola
    - gdb
    - git
    - gitk
    - htop
    - jq
    - libcairo2-dev
    - lynis  # Security scanning tool
    - nodejs
    - pkg-config
    - podman
    - python3-dbus
    - python3-psutil
    - seahorse  # key management
    - shellcheck
    - sqlitebrowser
    - sublime-merge
    - sublime-text
    - sysstat  # iostat
    - tree
    - unzip
    - wget
    - zsh

- name: Debian - Install non WSL packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - code  # VSCode
  when: not running_in_wsl

- name: Debian - Best effort to install optional packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - dconf-editor
    - exa
    - fd-find
    - neofetch
    - ripgrep
  failed_when: false

- name: Debian - Best effort to install remote packages
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.deb
    - https://prerelease.keybase.io/keybase_amd64.deb
  failed_when: false

### --- Distro specific ---

- name: Debian Packages
  ansible.builtin.import_tasks: debian/packages.yml
  when: ansible_distribution == 'Debian'

- name: Ubuntu Packages
  ansible.builtin.import_tasks: ubuntu/packages.yml
  when: ansible_distribution == 'Ubuntu'
