---
- name: Debian >=10 - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: debian10_install_packages
  until: debian10_install_packages is succeeded
  when: ansible_distribution_major_version | int >= 10
  loop:
    - npm

- name: Debian >=11 - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 3
  delay: 5
  register: debian11_install_packages
  until: debian11_install_packages is succeeded
  when: ansible_distribution_major_version | int >= 11
  loop:
    - kubernetes-client  # kubectl
    - python3-cairo  # required to fix default python
    # TODO: install yubikey-manager when debian finally updates to a non alpha
    # - yubikey-manager
    - zoxide  # A faster way to navigate your filesystem
