---
- name: Debian >=10 - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 5
  delay: 5
  when: ansible_distribution_major_version | int >= 10
  loop:
    - npm

- name: Debian >=11 - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  retries: 5
  delay: 5
  when: ansible_distribution_major_version | int >= 11
  loop:
    - kubernetes-client  # kubectl
    - python3-cairo  # required to fix default python
    # TODO: install yubikey-manager when debian finally updates to a non alpha
    # - yubikey-manager
    - zoxide  # A faster way to navigate your filesystem
