---
- name: Fedora - Import RPM-GPG-KEY-rpmfusion-free signing key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_free_fedora.key }}"
    fingerprint: "{{ signing_keys.rpmfusion_free_fedora.fingerprint }}"

- name: Fedora - Add RPMFusion-free repository
  ansible.builtin.dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/\
        rpmfusion-free-release-{{ ansible_distribution_major_version | int }}.noarch.rpm"
    state: present
  when: (not rpmfusion_free_repo.stat.exists) or
        (not rpmfusion_free_updates_repo.stat.exists)
  register: rpmfusion_free_install
  until: rpmfusion_free_install is succeeded
  retries: 5
  delay: 5

- name: Fedora - Import RPM-GPG-KEY-rpmfusion-nonfree signing key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_nonfree_fedora.key }}"
    fingerprint: "{{ signing_keys.rpmfusion_nonfree_fedora.fingerprint }}"

- name: Fedora - Add RPMFusion-nonfree repository
  ansible.builtin.dnf:
    name:
      - "https://download1.rpmfusion.org/nonfree/fedora/\
        rpmfusion-nonfree-release-{{ ansible_distribution_major_version | int }}.noarch.rpm"
    state: present
  when: (not rpmfusion_nonfree_repo.stat.exists) or
        (not rpmfusion_nonfree_updates_repo.stat.exists)
  register: rpmfusion_nonfree_install
  until: rpmfusion_nonfree_install is succeeded
  retries: 5
  delay: 5

- name: Fedora - Install zoom updater dependencies
  ansible.builtin.dnf:
    name:
      - make
      - coreutils  # provides basename
      - createrepo_c
      - curl
      - rpm
    state: present

- name: Fedora - install zoom updater service
  community.general.make:
    chdir: /opt/zoom-yum-repo
    target: install-service
  when:
    - stat_run_systemd.stat.exists
    - stat_run_systemd.stat.isdir

- name: Fedora - start zoom updater service
  community.general.make:
    chdir: /opt/zoom-yum-repo
    target: start-service
  when:
    - stat_run_systemd.stat.exists
    - stat_run_systemd.stat.isdir

### Version specific repositories
