---
- name: Fedora - Install docker
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - libcrypt.so.1()(64bit)  # needed by docker-compose
