---
- name: Fedora - Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - autojump-zsh
    - bat  # rust version of cat
    - code  # VSCode
    - community-mysql-devel  # from fedora modular
    - dbus-daemon
    - dbus-tools
    - fd-find
    - flameshot
    - fzf
    - gdouros-symbola-fonts
    - git-delta
    - google-noto-sans-display-fonts
    - google-noto-sans-display-vf-fonts
    - google-noto-sans-mono-fonts
    - google-noto-sans-mono-vf-fonts
    - google-noto-sans-vf-fonts
    - google-roboto-mono-fonts
    - gtk-murrine-engine  # gtk2 theme engine. Probably safe to remove
    - hyperfine  # CLI benchmarking
    - intel-media-driver
    - levien-inconsolata-fonts
    - mozilla-fira-fonts-common
    - mozilla-fira-mono-fonts
    - mozilla-fira-sans-fonts
    - podman
    - ShellCheck
    - sqlitebrowser
    - starship  # CLI prompt
    - tealdeer  # tldr writen in rust
    - texlive-montserrat
    - zoxide  # A faster way to navigate your filesystem

- name: Fedora >=29 - Install bluetooth codecs
  ansible.builtin.dnf:
    name:
      - pulseaudio-module-bluetooth-freeworld
    state: present
    allowerasing: true
  when: ansible_distribution_major_version|int >= 29
