---
- name: Fedora - Install packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - autojump-zsh
    - docker-ce
    - fd-find
    - gdouros-symbola-fonts
    - gtk-murrine-engine # gtk2 theme engine. Probably safe to remove
    - julia
    - levien-inconsolata-fonts
    - mozilla-fira-fonts-common
    - mozilla-fira-mono-fonts
    - mozilla-fira-sans-fonts
    - pssh
    - ShellCheck
    - sqlitebrowser

- name: Fedora >=26 - Install packages
  dnf:
    name:
      - flameshot
      - fzf
    state: present
  when: ansible_distribution_major_version|int >= 26

- name: Fedora >=27 - Install packages
  dnf:
    name:
      - containerd.io
      - docker-ce-cli
      - podman
    state: present
  when: ansible_distribution_major_version|int >= 27

- name: Fedora <=27 - Install mysql-community-devel
  dnf:
    name:
      - mysql-community-devel # from the community repository
    state: present
  when: ansible_distribution_major_version|int <= 27

- name: Fedora >=28 - Install packages
  dnf:
    name:
      - code
      - community-mysql-devel # from fedora modular
    state: present
  when: ansible_distribution_major_version|int >= 28

- name: Fedora >=29 - Install packages
  dnf:
    name:
      - bat
      - dbus-daemon
      - dbus-tools
      - intel-media-driver
      - texlive-montserrat
    state: present
  when: ansible_distribution_major_version|int >= 29

- name: Fedora >=29 - Install bluetooth codecs
  dnf:
    name:
      - pulseaudio-module-bluetooth-freeworld
    state: present
    allowerasing: yes
  when: ansible_distribution_major_version|int >= 29

- name: Fedora >=30 - Install Razer packages for device config
  dnf:
    name:
      - openrazer-meta
      - polychromatic  # razer device configuration
    state: present
  when: ansible_distribution_major_version|int >= 30
  ignore_errors: true

# This is for the razer drivers which run in userspace
- name: Fedora >=30 - Add user to plugdev group
  user:
    name: '{{ ansible_user_id }}'
    groups: plugdev
    append: true
  when: ansible_distribution_major_version|int >= 30
  ignore_errors: true

- name: Fedora >=31 - Install packages
  dnf:
    name:
      - git-delta
    state: present
  when: ansible_distribution_major_version|int >= 31

- name: Fedora >=32 - Install packages
  dnf:
    name:
      - libxcrypt-compat # docker-compose needs libcrypt.so.1 provided by this package
    state: present
  when: ansible_distribution_major_version|int >= 32

- name: Fedora >=32 - Install gitui
  dnf:
    name:
      - gitui
    state: present
  when: ansible_distribution_major_version|int >= 32
  ignore_errors: true
