---
# TODO import rpm key

- name: Fedora >=30 - Add Razer repository
  yum_repository:
    file: razer
    name: razer
    description: Razer drivers (Fedora {{ ansible_distribution_major_version|int }})
    baseurl: "https://download.opensuse.org/repositories/hardware:/razer/Fedora_{{ ansible_distribution_major_version|int }}/"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.opensuse.org/repositories/hardware:/razer/Fedora_{{ ansible_distribution_major_version|int }}/repodata/repomd.xml.key"
    repo_gpgcheck: true
  when: ansible_distribution_major_version|int >= 30

- name: Fedora >=30 - Install Razer packages for device config
  dnf:
    name:
      - openrazer-meta
      - polychromatic  # razer device configuration
    state: present
  when: ansible_distribution_major_version|int >= 30

# This is for the razer drivers which run in userspace
- name: Fedora >=30 - Add user to plugdev group
  user:
    name: '{{ ansible_user_id }}'
    groups: plugdev
    append: true
  when: ansible_distribution_major_version|int >= 30
