---
- name: Fedora - Import RPM-GPG-KEY-rpmfusion-free
  rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_free_fedora[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.rpmfusion_free_fedora[ansible_distribution_major_version].fingerprint }}"

- name: Fedora - Import RPM-GPG-KEY-rpmfusion-nonfree
  rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_nonfree_fedora[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.rpmfusion_nonfree_fedora[ansible_distribution_major_version].fingerprint }}"

# TODO import rpm key

- name: Fedora - Add Hashicorp repository
  yum_repository:
    file: hashicorp
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Fedora - Add RPMFusion-free repository
  dnf:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present
  when: (not rpmfusion_free_repo.stat.exists) or
        (not rpmfusion_free_updates_repo.stat.exists)
  register: rpmfusion_free_install
  until: rpmfusion_free_install is succeeded
  retries: 5
  delay: 5

- name: Fedora - Add RPMFusion-nonfree repository
  dnf:
    name:
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present
  when: (not rpmfusion_nonfree_repo.stat.exists) or
        (not rpmfusion_nonfree_updates_repo.stat.exists)
  register: rpmfusion_nonfree_install
  until: rpmfusion_nonfree_install is succeeded
  retries: 5
  delay: 5

- name: Fedora <=25 - Add MySQL community repository
  dnf:
    name:
      - "https://dev.mysql.com/get/mysql57-community-release-fc{{ ansible_distribution_major_version|int }}-10.noarch.rpm"
    state: present
  when: ansible_distribution_major_version|int <= 25

- name: Fedora 26,27 - Add MySQL community repository
  dnf:
    name:
      - "https://dev.mysql.com/get/mysql80-community-release-fc{{ ansible_distribution_major_version|int }}-1.noarch.rpm"
    state: present
  when:
    - ansible_distribution_major_version|int >= 26
    - ansible_distribution_major_version|int <= 27
