---
- name: Fedora - check if rpmfusion-free.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: rpmfusion_free_repo

- name: Fedora - check if rpmfusion-free-updates.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-free-updates.repo
  register: rpmfusion_free_updates_repo

- name: Fedora - Add RPMFusion-free repository
  dnf:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present
  when: (rpmfusion_free_repo.stat.exists == False) or
        (rpmfusion_free_updates_repo.stat.exists == False)
  register: rpmfusion_free_install
  until: rpmfusion_free_install is succeeded
  retries: 5
  delay: 5

- name: Fedora - check if rpmfusion-nonfree.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree.repo
  register: rpmfusion_nonfree_repo

- name: Fedora - check if rpmfusion-nonfree-updates.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
  register: rpmfusion_nonfree_updates_repo

- name: Fedora - Add RPMFusion-nonfree repository
  dnf:
    name:
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present
  when: (rpmfusion_nonfree_repo.stat.exists == False) or
        (rpmfusion_nonfree_updates_repo.stat.exists == False)
  register: rpmfusion_nonfree_install
  until: rpmfusion_nonfree_install is succeeded
  retries: 5
  delay: 5

- name: Fedora <=25 - Add MySQL community repository
  dnf:
    name:
      - "https://dev.mysql.com/get/mysql57-community-release-fc{{ ansible_distribution_major_version|int }}-10.noarch.rpm"
    state: present
  when: ansible_distribution_major_version|int <= 25

- name: Fedora 26,27 - Add MySQL community repository
  dnf:
    name:
      - "https://dev.mysql.com/get/mysql80-community-release-fc{{ ansible_distribution_major_version|int }}-1.noarch.rpm"
    state: present
  when:
    - ansible_distribution_major_version|int >= 26
    - ansible_distribution_major_version|int <= 27

- name: Fedora >=30 - Add Razer repository
  yum_repository:
    file: razer
    name: razer
    description: Razer drivers (Fedora {{ ansible_distribution_major_version|int }})
    baseurl: "https://download.opensuse.org/repositories/hardware:/razer/Fedora_{{ ansible_distribution_major_version|int }}/"
    enabled: yes
    gpgcheck: yes
    gpgkey: "https://download.opensuse.org/repositories/hardware:/razer/Fedora_{{ ansible_distribution_major_version|int }}/repodata/repomd.xml.key"
    repo_gpgcheck: yes
  when: ansible_distribution_major_version|int >= 30

- name: Fedora >=31 - Add lazygit repository
  command:
    cmd: dnf copr enable atim/lazygit -y
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:lazygit.repo
  when: ansible_distribution_major_version|int >= 31

# TODO: remove this once a F32 repo is available
- name: Fedora 32 - Add Docker repository for Fedora 31
  tags: [ docker ]
  yum_repository:
    file: docker-ce
    name: docker-ce-stable
    description: "Docker CE Stable - {{ ansible_distribution }} - 31 - $basearch"
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/31/$basearch/stable"
  when: ansible_distribution_major_version|int == 32
