---
- name: RedHat - Import GCloud Yum Key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    fingerprint: 7F92E05B31093BEF5A3C2D38FEEA9169307EA071

- name: RedHat - Import GCloud Package Key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    fingerprint: 3749E1BA95A86CE054546ED2F09C394C3E1BA8D5

- name: RedHat - Add Google Cloud SDK repository
  ansible.builtin.yum_repository:
    file: google-cloud-sdk
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: RedHat - Install gcloud
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - google-cloud-sdk
