---
- name: RedHat - rpm keys for Google
  ansible.builtin.import_tasks: rpm_keys_google.yml

- name: RedHat - Import google-cloud-sdk repository key - 1
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64/repodata/repomd.xml.key
    fingerprint: 7F92E05B31093BEF5A3C2D38FEEA9169307EA071
  register: import_glcoud_repository_key1

- name: RedHat - Import google-cloud-sdk repository key - 2
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64/repodata/repomd.xml.key
    fingerprint: 59FE0256827269DC81578F928B57C5C2836F4BEB
  register: import_glcoud_repository_key2

- name: RedHat - Add Google Cloud SDK repository
  ansible.builtin.yum_repository:
    file: google-cloud-sdk
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      # Repository metadata keys
      - https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64/repodata/repomd.xml.key
      # Old repository metadata key
      # - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      # Package key
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

# TODO: remove this workaround when dnf uses the rpm key database
- name: RedHat - refresh dnf keys for google-cloud-sdk  # noqa no-handler
  ansible.builtin.command: "dnf -q makecache -y --disablerepo='*' --enablerepo='google-cloud-sdk'"
  when: >
    import_glcoud_repository_key1.changed
    or import_glcoud_repository_key2.changed
    or import_glcoud_package_key.changed

- name: RedHat - Install gcloud
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - google-cloud-cli
