---
- name: RedHat - rpm keys for Google
  ansible.builtin.import_tasks: rpm_keys_google.yml

- name: RedHat - Import kubernetes repository key - 1
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml.key
    fingerprint: 7F92E05B31093BEF5A3C2D38FEEA9169307EA071
  register: import_kubernetes_repository_key1

- name: RedHat - Import kubernetes repository key - 2
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml.key
    fingerprint: 59FE0256827269DC81578F928B57C5C2836F4BEB
  register: import_kubernetes_repository_key2

- name: RedHat - Add Kubernetes repository
  ansible.builtin.yum_repository:
    file: kubernetes
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      # Repository metadata keys
      - https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64/repodata/repomd.xml.key
      # Old repository metadata key
      # - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      # Package key
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

# TODO: remove this workaround when dnf uses the rpm key database
- name: RedHat - refresh dnf keys for Google  # noqa no-handler
  ansible.builtin.command: "dnf -q makecache -y --disablerepo='*' --enablerepo='kubernetes'"
  when: import_kubernetes_repository_key1.changed or import_kubernetes_repository_key2.changed or import_glcoud_package_key.changed

- name: RedHat - Install kubernetes
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - kubectl
