---
- name: RedHat - Kernel Devel
  ansible.builtin.dnf:
    # Disable updates so on fresh installs this will get the headers matching the current version
    disablerepo: updates
    name:
      - kernel-headers
      - kernel-devel
    state: present

# Need to upgrade vim-minimal first, otherwise there are conflicts
- name: RedHat - Update vim-minimal
  ansible.builtin.dnf:
    name:
      - vim-minimal
    state: present

# Install vim separately due to conflicts in upgrade / install
- name: RedHat - Update vim
  ansible.builtin.dnf:
    name:
      - vim
    state: present

- name: RedHat - Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - 1password
    - autoconf
    - automake
    - bash
    - bash-completion
    - bison
    - bzip2
    - bzip2-devel
    - cmake
    - curl
    - dconf
    - dnf-automatic
    - flatpak
    - gcc
    - gcc-c++
    - gdb
    - git
    - gitk
    - graphviz
    - jq
    - libcurl-devel
    - libffi-devel
    - libnotify
    - libtool
    - make
    - nodejs
    - npm
    - openssl-devel
    - patch
    - pcp-system-tools  # dstat
    - perl
    - python3-dbus
    - python3-devel
    - python3-psutil
    - readline-devel
    - redhat-lsb
    - redhat-rpm-config
    - samba-client
    - seahorse  # key management
    - setools-console
    - sqlite-devel
    - sublime-merge
    - sublime-text
    - sysstat  # iostat
    - tree
    - virt-what
    - wget
    - xz
    - xz-devel
    - zlib-devel
    - zsh

- name: RedHat - Best effort to install keybase
  ansible.builtin.dnf:
    name:
      - keybase
    state: present
  when: rpm_key_keybase is succeeded

- name: RedHat - Best effort to install optional packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - crudini
    - dconf-editor
    - dkms
    - exa
    - fuse-sshfs
    - google-noto-sans-fonts
    - google-roboto-condensed-fonts
    - google-roboto-fonts
    - google-roboto-slab-fonts
    - htop
    - ImageMagick
    - libheif
    - libyaml-devel
    - lynis  # Security scanning tool
    - mint-y-icons
    - mint-y-theme
    - ncdu
    - neofetch
    - p7zip
    - pv
    - ripgrep
    - ytop  # CLI system monitoring
    # TODO: enable this again when yubikey-manager fixes the constraints around cryptography
    # - yubikey-manager
    - zoom
  failed_when: false

- name: RedHat - Install unsigned remote packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  loop:
    - https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.rpm

### --- Distro specific ---

- name: CentOS Packages
  ansible.builtin.import_tasks: centos/packages.yml
  when: ansible_distribution == 'CentOS'

- name: Fedora Packages
  ansible.builtin.import_tasks: fedora/packages.yml
  when: ansible_distribution == 'Fedora'
