---
- name: RedHat - Kernel Devel
  dnf:
    # Disable updates so on fresh installs this will get the headers matching the current version
    disablerepo: updates
    name:
      - kernel-headers
      - kernel-devel
    state: present

# Need to upgrade vim-minimal first, otherwise there are conflicts
- name: RedHat - Update vim-minimal
  dnf:
    name:
      - vim-minimal
    state: present

# Install vim separately due to conflicts in upgrade / install
- name: RedHat - Update vim
  dnf:
    name:
      - vim
    state: present

- name: RedHat - Install packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - 1password
    - autoconf
    - automake
    - bash
    - bash-completion
    - bison
    - bzip2
    - bzip2-devel
    - cmake
    - crudini
    - curl
    - dconf
    - dkms
    - dnf-automatic
    - flatpak
    - fuse-sshfs
    - gcc
    - gcc-c++
    - gdb
    - git
    - gitk
    - google-cloud-sdk
    - google-noto-sans-display-fonts.noarch
    - google-noto-sans-display-vf-fonts.noarch
    - google-noto-sans-fonts
    - google-noto-sans-mono-fonts
    - google-noto-sans-mono-vf-fonts
    - google-noto-sans-vf-fonts
    - google-roboto-condensed-fonts
    - google-roboto-fonts
    - google-roboto-mono-fonts
    - google-roboto-slab-fonts
    - graphviz
    - htop
    - ImageMagick
    - jq
    - keybase
    - kubectl
    - libcurl-devel
    - libffi-devel
    - libheif
    - libnotify
    - libtool
    - libyaml-devel
    - make
    - ncdu
    - nodejs
    - npm
    - openssl-devel
    - p7zip
    - patch
    - pcp-system-tools # dstat
    - perl
    - pv
    - python3-dbus
    - python3-devel
    - readline-devel
    - redhat-lsb
    - redhat-rpm-config
    - samba-client
    - seahorse # key management
    - setools-console
    - sqlite-devel
    - sublime-merge
    - sublime-text
    - sysstat # iostat
    - tree
    - virt-what
    - wget
    - xz
    - xz-devel
    - zlib-devel
    - zsh

- name: RedHat - Best effort to install optional packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - exa
  ignore_errors: true

- name: RedHat - Install remote packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - https://zoom.us/client/latest/zoom_x86_64.rpm

- name: RedHat - Install unsigned remote packages
  dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  loop:
    - https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.rpm

### --- Distro specific ---

- name: CentOS Packages
  import_tasks: centos/packages.yml
  when: ansible_distribution == 'CentOS'

- name: Fedora Packages
  import_tasks: fedora/packages.yml
  when: ansible_distribution == 'Fedora'
