---
- name: RedHat - Add dnf plugins
  dnf:
    name:
      - dnf-plugins-core

- name: RedHat - Import 1Password signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc
    fingerprint: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

- name: RedHat - Add 1Password beta repository
  ansible.builtin.yum_repository:
    file: 1password-ansible
    name: 1password-beta
    description: 1Password - Beta
    baseurl: https://downloads.1password.com/linux/rpm/beta/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    repo_gpgcheck: true

- name: RedHat - Add 1Password stable repository
  ansible.builtin.yum_repository:
    file: 1password-ansible
    name: 1password-stable
    description: 1Password - Stable
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    repo_gpgcheck: true

- name: RedHat - Import Keybase signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://keybase.io/docs/server_security/code_signing_key.asc
    fingerprint: 222B85B0F90BE2D24CFEB93F47484E50656D16C7

- name: RedHat - Add Keybase repository
  ansible.builtin.yum_repository:
    file: keybase
    name: keybase
    description: keybase
    baseurl: http://prerelease.keybase.io/rpm/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
    metadata_expire: '60'
    # This repo was previously signed with the key but they no longer sign the
    # repo when publishing new releases. This causes a bad signature.
    repo_gpgcheck: false

- name: RedHat - Import Sublime-Text signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    fingerprint: 1B64279675A4299DCFC70858CA464A9A222D23D0

- name: RedHat - Add Sublime-Text repository
  ansible.builtin.yum_repository:
    file: sublime-text
    name: sublime-text
    description: Sublime Text - x86_64 - Stable
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    gpgkey:
      - https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    repo_gpgcheck: true

- name: RedHat - Import VSCode signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
    fingerprint: BC528686B50D79E339D3721CEB3E94ADBE1229CF

- name: RedHat - Add VSCode repository
  ansible.builtin.yum_repository:
    file: vscode
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    repo_gpgcheck: true

- name: RedHat - Import Zoom signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://zoom.us/linux/download/pubkey
    fingerprint: 396060CADD8A75220BFCB369B903BF1861A7C71D

- name: RedHat - check if rpmfusion-free.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: rpmfusion_free_repo

- name: RedHat - check if rpmfusion-free-updates.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-free-updates.repo
  register: rpmfusion_free_updates_repo

- name: RedHat - check if rpmfusion-nonfree.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree.repo
  register: rpmfusion_nonfree_repo

- name: RedHat - check if rpmfusion-nonfree-updates.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
  register: rpmfusion_nonfree_updates_repo

### --- Distro specific ---

- name: Fedora Repositories
  import_tasks: fedora/repositories.yml
  when: ansible_distribution == 'Fedora'
