---
- name: RedHat - Add dnf plugins
  dnf:
    name:
      - dnf-plugins-core

- name: RedHat - Import 1Password signing key
  rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc
    fingerprint: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

- name: RedHat - Import Zoom signing key
  rpm_key:
    state: present
    key: https://zoom.us/linux/download/pubkey
    fingerprint: 396060CADD8A75220BFCB369B903BF1861A7C71D

- name: RedHat - Add 1Password beta repository
  yum_repository:
    file: 1password-ansible
    name: 1password-beta
    description: 1Password - Beta
    baseurl: https://downloads.1password.com/linux/rpm/beta/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    repo_gpgcheck: true

- name: RedHat - Add 1Password stable repository
  yum_repository:
    file: 1password-ansible
    name: 1password-stable
    description: 1Password - Stable
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    repo_gpgcheck: true

- name: RedHat - Check for Docker support
  tags: [docker]
  uri:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version|int }}/{{ ansible_architecture }}/stable"
  register: uri_docker_repo_rpm
  ignore_errors: true

- name: RedHat - Add Docker repository
  tags: [docker]
  yum_repository:
    file: docker-ce
    name: docker-ce-stable
    description: "Docker CE Stable - {{ ansible_distribution }} - $releasever - $basearch"
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/$releasever/$basearch/stable"
    enabled: "{{ uri_docker_repo_rpm is succeeded }}"
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    repo_gpgcheck: true

# Useful to configure on new Fedora versions that do not have docker support yet
- name: RedHat - Disable Docker Test repository
  tags: [docker]
  yum_repository:
    file: docker-ce
    name: docker-ce-test
    description: "Docker CE Test - {{ ansible_distribution }} - $releasever - $basearch"
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/$releasever/$basearch/test"
    enabled: false
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    repo_gpgcheck: true

- name: RedHat - Add Google Cloud SDK repository
  yum_repository:
    file: google-cloud-sdk
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: RedHat - Add Keybase repository
  yum_repository:
    file: keybase
    name: keybase
    description: keybase
    baseurl: http://prerelease.keybase.io/rpm/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
    metadata_expire: '60'

- name: RedHat - Add Kubernetes repository
  yum_repository:
    file: kubernetes
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: RedHat - Add Sublime-Text repository
  yum_repository:
    file: sublime-text
    name: sublime-text
    description: Sublime Text - x86_64 - Stable
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    gpgkey:
      - https://download.sublimetext.com/sublimehq-rpm-pub.gpg

- name: RedHat - Add VSCode repository
  yum_repository:
    file: vscode
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    repo_gpgcheck: true

- name: RedHat - check if rpmfusion-free.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: rpmfusion_free_repo

- name: RedHat - check if rpmfusion-free-updates.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-free-updates.repo
  register: rpmfusion_free_updates_repo

- name: RedHat - check if rpmfusion-nonfree.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree.repo
  register: rpmfusion_nonfree_repo

- name: RedHat - check if rpmfusion-nonfree-updates.repo file exists
  stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
  register: rpmfusion_nonfree_updates_repo

### --- Distro specific ---

- name: Fedora Repositories
  import_tasks: fedora/repositories.yml
  when: ansible_distribution == 'Fedora'
