---
- name: RedHat - Import GCloud Package Key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    fingerprint: 3749E1BA95A86CE054546ED2F09C394C3E1BA8D5
  register: import_glcoud_package_key
