---
- name: All - Git update pyenv  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/Applications/pyenv

- name: All - Git update pyenv plugins  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/Applications/pyenv/plugins/{{ item.name }}"
  loop:
    - repo: https://gitlab.com/perobertson/pyenv-default-requirements.git
      name: pyenv-default-requirements
    - repo: https://github.com/pyenv/pyenv-doctor.git
      name: pyenv-doctor
    - repo: https://github.com/pyenv/pyenv-virtualenv.git
      name: pyenv-virtualenv

- name: All - Git update rbenv  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/Applications/rbenv
  register: git_rbenv

- name: All - Git update rbenv - ruby build  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/Applications/rbenv/plugins/ruby-build
  register: git_ruby_build

- name: All - Configure rbenv  # noqa no-handler
  ansible.builtin.command:
    chdir: ~/Applications/rbenv
    cmd: src/configure
  when: git_rbenv is changed or git_ruby_build is changed

- name: All - Make rbenv  # noqa no-handler
  ansible.builtin.command:
    chdir: ~/Applications/rbenv
    cmd: make -C src
  when: git_rbenv is changed or git_ruby_build is changed

- name: All - Git update tools  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://gitlab.com/perobertson/cli-tools.git
    dest: ~/Applications/cli-tools

# Needed for user systemd scripts
- name: All - Create ~/bin
  tags: [systemd]
  ansible.builtin.file:
    path: $HOME/bin
    state: directory
    mode: '0700'

- name: All - Populate ~/bin
  tags: [systemd]
  diff: true
  ansible.builtin.copy:
    src: "files/home/user/bin/{{ item.name }}"
    dest: "$HOME/bin/{{ item.name }}"
    mode: "{{ item.mode }}"
  loop:
    - name: README.md
      mode: '0600'

# For user systemd
# https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory
- name: All - Create ~/.local/bin
  tags: [systemd]
  ansible.builtin.file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - .local/bin
    - .local/lib

- name: All - Populate user systemd scripts
  tags: [systemd]
  diff: true
  ansible.builtin.copy:
    src: "files/home/user/.local/bin/{{ item.name }}"
    dest: "$HOME/.local/bin/{{ item.name }}"
    mode: "{{ item.mode }}"
  loop:
    - name: pkenv-update
      mode: '0700'
    - name: tfenv-update
      mode: '0700'

- name: All - pkenv-update
  ansible.builtin.command:
    cmd: "$HOME/.local/bin/pkenv-update"
  register: pkenv_update_result
  changed_when: pkenv_update_result.stdout != 'Already up to date.'

- name: All - tfenv-update
  ansible.builtin.command:
    cmd: "$HOME/.local/bin/tfenv-update"
  register: tfenv_update_result
  changed_when: tfenv_update_result.stdout != 'Already up to date.'
