---
- name: All - Git update pyenv
  diff: false
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/Applications/pyenv

- name: All - Git update pyenv plugins
  diff: false
  git:
    repo: "{{ item.repo }}"
    dest: "~/Applications/pyenv/plugins/{{ item.name }}"
  loop:
    - repo: https://gitlab.com/perobertson/pyenv-default-requirements.git
      name: pyenv-default-requirements
    - repo: https://github.com/pyenv/pyenv-doctor.git
      name: pyenv-doctor
    - repo: https://github.com/pyenv/pyenv-virtualenv.git
      name: pyenv-virtualenv

- name: All - Git update rbenv
  diff: false
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/Applications/rbenv

- name: All - Git update rbenv - ruby build
  diff: false
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/Applications/rbenv/plugins/ruby-build

- name: All - Configure rbenv
  command:
    chdir: ~/Applications/rbenv
    cmd: src/configure

- name: All - Make rbenv
  command:
    chdir: ~/Applications/rbenv
    cmd: make -C src

- name: All - Git update tfenv
  diff: false
  git:
    repo: https://github.com/tfutils/tfenv.git
    dest: ~/Applications/tfenv
