---
- name: All - Git update pkenv  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://github.com/iamhsa/pkenv.git
    dest: ~/Applications/pkenv

- name: All - Git update pyenv  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/Applications/pyenv

- name: All - Git update pyenv plugins  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/Applications/pyenv/plugins/{{ item.name }}"
  loop:
    - repo: https://gitlab.com/perobertson/pyenv-default-requirements.git
      name: pyenv-default-requirements
    - repo: https://github.com/pyenv/pyenv-doctor.git
      name: pyenv-doctor
    - repo: https://github.com/pyenv/pyenv-virtualenv.git
      name: pyenv-virtualenv

- name: All - Git update rbenv  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/Applications/rbenv
  register: git_rbenv

- name: All - Git update rbenv - ruby build  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/Applications/rbenv/plugins/ruby-build
  register: git_ruby_build

- name: All - Configure rbenv  # noqa no-handler
  ansible.builtin.command:
    chdir: ~/Applications/rbenv
    cmd: src/configure
  when: git_rbenv is changed or git_ruby_build is changed

- name: All - Make rbenv  # noqa no-handler
  ansible.builtin.command:
    chdir: ~/Applications/rbenv
    cmd: make -C src
  when: git_rbenv is changed or git_ruby_build is changed

- name: All - Git update tfenv  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://github.com/tfutils/tfenv.git
    dest: ~/Applications/tfenv

- name: All - Git update tools  # noqa git-latest
  diff: false
  ansible.builtin.git:
    repo: https://gitlab.com/perobertson/cli-tools.git
    dest: ~/Applications/cli-tools

# Needed for user systemd scripts
- name: All - Create user ~/bin
  ansible.builtin.file:
    path: $HOME/bin
    state: directory
    mode: '0700'

- name: All - Create user scripts
  diff: true
  ansible.builtin.copy:
    src: "files/home/user/bin/{{ item.name }}"
    dest: "$HOME/bin/{{ item.name }}"
    mode: "{{ item.mode }}"
  loop:
    - name: README.md
      mode: '0600'

- name: All - Create user ~/.config/systemd/user
  ansible.builtin.file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - .config/systemd
    - .config/systemd/user

- name: All - Create user services
  diff: true
  ansible.builtin.copy:
    src: "files/home/user/.config/systemd/user/{{ item.name }}"
    dest: "$HOME/.config/systemd/user/{{ item.name }}"
    mode: "{{ item.mode }}"
  loop:
    - name: logout-podman-stop.service
      mode: '0600'

- name: All - Enable user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
    scope: user
  when: not file_dockerenv.stat.exists
  loop:
    - logout-podman-stop.service
  # TODO: figure out how to get `systemd --user` running
  # Failed to connect to bus: No such file or directory
  ignore_errors: true
