---
- name: All - Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: All - Create user systemd config directory
  file:
    path: ~/.config/systemd/user
    state: directory

- name: All - Add flatpak auto updates
  diff: true
  copy:
    src: files/home/user/.config/systemd/user/{{ item }}
    dest: ~/.config/systemd/user/{{ item }}
  loop:
    - flatpak-update.service
    - flatpak-update.timer

- name: All - Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop:
    - com.discordapp.Discord
    - com.slack.Slack
    - com.spotify.Client
    - org.videolan.VLC
  register: flatpak_install
  until: flatpak_install is succeeded
  retries: 5
  delay: 5
