---
- name: All - Add the flathub flatpak repository remote to the user installation
  tags: [ user, flatpak ]
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: All - Create user systemd config directory
  tags: [ user, flatpak ]
  file:
    path: ~/.config/systemd/user
    state: directory

- name: All - Add flatpak auto updates
  tags: [ user, flatpak ]
  diff: true
  copy:
    src: files/home/user/.config/systemd/user/{{ item }}
    dest: ~/.config/systemd/user/{{ item }}
  loop:
    - flatpak-update.service
    - flatpak-update.timer

- name: All - Install flatpaks
  tags: [ user, flatpak ]
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop:
    - com.discordapp.Discord
    - com.slack.Slack
    - com.spotify.Client
