---
- name: All - Sublime Create packages directory
  file:
    path: $HOME/.config/sublime-text-3/Installed Packages
    state: directory
    mode: '0700'

- name: All - Sublime Create user packages directory
  file:
    path: $HOME/.config/sublime-text-3/Packages/User
    state: directory
    mode: '0700'

- name: All - Sublime check if package control exists
  stat:
    path: $HOME/.config/sublime-text-3/Installed Packages/Package Control.sublime-package
  register: sublime_package_control

- name: All - Sublime download package control
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: $HOME/.config/sublime-text-3/Installed Packages/Package Control.sublime-package
  when: not sublime_package_control.stat.exists

- name: All - VSCode installed extensions # noqa 301
  command: code --list-extensions
  register: vscode_extensions

- name: All - VSCode install extensions
  command: code --install-extension {{ item }}
  when: "item not in vscode_extensions['stdout_lines'] | map('lower')"
  loop:
    - bungcip.better-toml
    - coolbear.systemd-unit-file
    - davidanson.vscode-markdownlint
    - eamodio.gitlens
    - editorconfig.editorconfig
    - gitlab.gitlab-workflow
    - golang.go
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-vscode.vscode-typescript-tslint-plugin
    - rust-lang.rust
    - timonwong.shellcheck
