---
- name: All - find pyenv-default-requirements
  ansible.builtin.find:
    paths: "${HOME}/.config/pyenv-default-requirements/requirements.d/"
    file_type: any
  register: pyenv_default_requirement_files

- name: All - pip install pyenv-default-requirements  # noqa package-latest
  ansible.builtin.pip:
    extra_args: --user
    requirements: "{{ item.path }}"
    state: latest
  loop: "{{ pyenv_default_requirement_files.files }}"
  register: pip_out

# TODO: move this to a handler
- name: All - pip check  # noqa no-handler
  ansible.builtin.command: pip check
  when: pip_out.changed
