---
- name: All - Fetch gsettings schemas
  no_log: true
  command: gsettings list-schemas
  ignore_errors: yes
  register: gsettings_schemas

- name: All - Show clock seconds
  command: gsettings set org.cinnamon.desktop.interface clock-show-seconds true
  when: "'org.cinnamon.desktop.interface' in gsettings_schemas.stdout_lines"

- name: All - Set monospace font
  command: gsettings set org.gnome.desktop.interface monospace-font-name 'Inconsolata 14'
  when: "'org.gnome.desktop.interface' in gsettings_schemas.stdout_lines"

- name: All - Files date format
  command: gsettings set org.nemo.preferences date-format 'iso'
  when: "'org.nemo.preferences' in gsettings_schemas.stdout_lines"

- name: All - Files default folder view
  command: gsettings set org.nemo.preferences default-folder-viewer 'list-view'
  when: "'org.nemo.preferences' in gsettings_schemas.stdout_lines"

- name: All - Configure Xresources
  diff: true
  copy:
    src: files/home/user/.Xresources
    dest: ~/.Xresources

- name: All - Set terminal settings
  tags: [ terminal ]
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:e7aeecbb-8907-4e08-916e-749914c7b0b7/{{ item.key }}"
    value: "{{ item.value | string }}"
    state: present
  loop:
    - key: audible-bell
      value: "false"
    - key: background-color
      value: "'rgb(46,52,54)'"
    - key: background-transparency-percent
      value: 7
    - key: bold-is-bright
      value: "false"
    - key: font
      value: "'Fira Mono 14'"
    - key: foreground-color
      value: "'rgb(211,215,207)'"
    - key: palette
      value:
        - 'rgb(7,54,66)'
        - 'rgb(220,50,47)'
        - 'rgb(133,153,0)'
        - 'rgb(181,137,0)'
        - 'rgb(38,139,210)'
        - 'rgb(211,54,130)'
        - 'rgb(42,161,152)'
        - 'rgb(238,232,213)'
        - 'rgb(0,43,54)'
        - 'rgb(203,75,22)'
        - 'rgb(88,110,117)'
        - 'rgb(101,123,131)'
        - 'rgb(131,148,150)'
        - 'rgb(108,113,196)'
        - 'rgb(147,161,161)'
        - 'rgb(253,246,227)'
    - key: text-blink-mode
      value: "'always'"
    - key: use-system-font
      value: "true"
    - key: use-theme-colors
      value: "true"
    - key: use-transparent-background
      value: "true"
    - key: visible-name
      value: "'Managed by Ansible'"

- name: All - Discover gnome terminal profiles
  tags: [ terminal ]
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/list"
    state: read
  register: gnome_terminal_profiles

- name: All - Parse gnome terminal profiles
  tags: [ terminal ]
  set_fact:
    gnome_terminal_profiles_list: "{{ gnome_terminal_profiles.value or '[]' | replace(\"'\", '\"') | from_json }}"

- name: All - Append new profile id to list
  tags: [ terminal ]
  set_fact:
    # list.append returns None which is falsey so use or to print out the updated value
    updated_gnome_terminal_profiles_list: "{{ gnome_terminal_profiles_list.append('e7aeecbb-8907-4e08-916e-749914c7b0b7') or gnome_terminal_profiles_list | unique | sort }}"

- name: All - Format gnome terminal list to dconf format
  tags: [ terminal ]
  set_fact:
    updated_gnome_terminal_profiles_str: "{{ updated_gnome_terminal_profiles_list | string | regex_replace('\"', \"'\") }}"

- name: All - Add profile to terminal list
  tags: [ terminal ]
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/list"
    value: "{{ updated_gnome_terminal_profiles_str | string }}"
    state: present

- name: All - Set default gnome terminal
  tags: [ terminal ]
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/default"
    value: "'e7aeecbb-8907-4e08-916e-749914c7b0b7'"
    state: present

- name: All - Enable cinnamon indicators
  tags: [ cinnamon ]
  dconf:
    key: /org/cinnamon/enable-indicators
    value: 'true'
    state: present

- name: All - Git update cinnamon-spices-themes
  tags: [ cinnamon ]
  diff: false
  git:
    repo: https://github.com/linuxmint/cinnamon-spices-themes.git
    dest: ~/Applications/cinnamon-spices-themes
    depth: 1

- name: All - Create ~/.themes dir
  tags: [ cinnamon ]
  file:
    path: ~/.themes
    state: directory

- name: All - Link cinnamon themes
  tags: [ cinnamon ]
  file:
    src: "~/Applications/cinnamon-spices-themes/{{ item }}/files/{{ item }}"
    dest: "~/.themes/Ansible-{{ item }}"
    state: link
  loop:
    - CBlack

- name: All - Set cinnamon theme
  tags: [ cinnamon ]
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - key: /org/cinnamon/theme/name
      value: "'Ansible-CBlack'"
    - key: /org/cinnamon/desktop/wm/preferences/theme
      value: "'Ansible-CBlack'"
    - key: /org/cinnamon/desktop/interface/gtk-theme
      value: "'Ansible-CBlack'"
