---
# TODO this is missing the fingerprint
- name: Debian - Add Docker signing key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Debian - Add Docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb['codename'] }} stable"
    filename: docker
    state: present

- name: Debian - Update apt cache
  apt:
    update_cache: true

- name: Debian - Install docker
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
