---
- name: Debian - Update apt cache
  apt:
    update_cache: yes

- name: Debian - Install packages
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - 1password
    - bash
    - bash-completion
    - code
    - containerd.io
    - crudini
    - dconf-cli
    - docker-ce
    - docker-ce-cli
    - flatpak
    - fonts-symbola
    - gdb
    - git
    - gitk
    - htop
    - jq
    - libcairo2-dev
    - libglib2.0-bin # gsettings
    - lynis # Security scanning tool
    - nodejs
    - npm
    - pkg-config
    - python3-dbus
    - python3-psutil
    - seahorse # key management
    - shellcheck
    - sqlitebrowser
    - sublime-merge
    - sublime-text
    - sysstat # iostat
    - tree
    - wget
    - zsh

- name: Debian - Best effort to install optional packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - exa
  ignore_errors: true

- name: Debian - Install remote packages
  apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.deb
    - https://prerelease.keybase.io/keybase_amd64.deb

### --- Distro specific ---

- name: Ubuntu Packages
  import_tasks: ubuntu/packages.yml
  when: ansible_distribution == 'Ubuntu'
