---
- name: Debian - Install packages
  apt:
    pkg:
      - containerd.io
      - docker-ce-cli
      - libcairo2-dev
      - libglib2.0-bin # gsettings
      - pkg-config
    state: present

- name: Debian - Install remote packages
  apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.deb

### --- Distro specific ---

- name: Ubuntu Packages
  import_tasks: ubuntu/packages.yml
  when: ansible_distribution == 'Ubuntu'
