---
- name: Debian - Install packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - bash
    - bash-completion
    - code
    - crudini
    - dconf-cli
    - flatpak
    - fonts-symbola
    - gdb
    - git
    - gitk
    - htop
    - jq
    - libcairo2-dev
    - libglib2.0-bin  # gsettings
    - lynis  # Security scanning tool
    - nodejs
    - pkg-config
    - python3-dbus
    - python3-psutil
    - seahorse  # key management
    - shellcheck
    - sqlitebrowser
    - sublime-merge
    - sublime-text
    - sysstat  # iostat
    - tree
    - wget
    - zsh

- name: Debian - Best effort to install optional packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - exa
    - fd-find
  failed_when: false

- name: Debian - Install remote packages
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.deb
    - https://prerelease.keybase.io/keybase_amd64.deb

### --- Distro specific ---

- name: Debian Packages
  ansible.builtin.import_tasks: debian/packages.yml
  when: ansible_distribution == 'Debian'

- name: Ubuntu Packages
  ansible.builtin.import_tasks: ubuntu/packages.yml
  when: ansible_distribution == 'Ubuntu'
