---
- name: Debian - Add Docker signing key
  tags: [ docker ]
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Debian - Add Docker repo
  tags: [ docker ]
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb['codename'] }} stable"
    filename: docker
    state: present

- name: Debian - Add Sublime-Text signing key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Debian - Add Sublime Text Repo
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: sublime-text
    state: present

### --- Distro specific ---

- name: Ubuntu Repositories
  import_tasks: tasks/system/debian/ubuntu/repositories.yml
  when: ansible_distribution == 'Ubuntu'
