---
- name: Debian - Add VSCode signing key
  shell:
    cmd: |
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
      install -o root -g root -m 644 /tmp/packages.microsoft.gpg /usr/share/keyrings/
      rm /tmp/packages.microsoft.gpg
    creates: /usr/share/keyrings/packages.microsoft.gpg

- name: Debian - Add VSCode Repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
    filename: vscode
    state: present

- name: Debian - Add Docker signing key
  tags: [ docker ]
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Debian - Add Docker repo
  tags: [ docker ]
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb['codename'] }} stable"
    filename: docker
    state: present

- name: Debian - Add Sublime-Text signing key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Debian - Add Sublime Text Repo
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: sublime-text
    state: present

### --- Distro specific ---

- name: Ubuntu Repositories
  import_tasks: ubuntu/repositories.yml
  when: ansible_distribution == 'Ubuntu'
