---
- name: Debian - Add 1Password signing key
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    state: present
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg

- name: Debian - Add 1Password Beta Repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 beta main"
    filename: 1password
    state: present

- name: Debian - Add 1Password Stable Repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
    filename: 1password
    state: present

- name: Debian - Check for Hashicorp support
  ansible.builtin.uri:
    url: https://apt.releases.hashicorp.com/dists/{{ ansible_distribution_release }}/Release
    method: HEAD
  register: uri_apt_hashicorp
  # fail with error if status is unexpected
  failed_when: uri_apt_hashicorp.status is undefined or uri_apt_hashicorp.status <= 0

- name: Debian - Add Hashicorp signing key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Debian - Add Hashicorp Repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
    state: present
  when: uri_apt_hashicorp.status == 200

- name: Debian - Add VSCode signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    keyring: /usr/share/keyrings/packages.microsoft.gpg

- name: Debian - Add VSCode Repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
    filename: vscode
    state: present

- name: Debian - Add Sublime-Text signing key
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
    id: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
    keyring: /usr/share/keyrings/sublime-archive-keyring.gpg

- name: Debian - Add Sublime Text Repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/sublime-archive-keyring.gpg] https://download.sublimetext.com/ apt/stable/
    filename: sublime-text
    state: present

### --- Distro specific ---

- name: Debian Repositories
  ansible.builtin.import_tasks: debian/repositories.yml
  when: ansible_distribution == 'Debian'

- name: Ubuntu Repositories
  ansible.builtin.import_tasks: ubuntu/repositories.yml
  when: ansible_distribution == 'Ubuntu'

### --- Post repo setup steps ---

- name: Debian - Update apt cache
  ansible.builtin.apt:
    update_cache: true
