---
- name: Debian >=10 - Install packages
  ansible.builtin.apt:
    pkg:
      - 1password
      - 1password-cli
      - npm
    state: present
  when: ansible_distribution_major_version | int >= 10

- name: Debian >=11 - Install packages
  ansible.builtin.apt:
    pkg:
      - kubernetes-client  # kubectl
      - podman
      - python3-cairo  # required to fix default python
      - zoxide  # A faster way to navigate your filesystem
    state: present
  when: ansible_distribution_major_version | int >= 11
