---
- name: Debian >=10 - Install packages
  ansible.builtin.apt:
    pkg:
      - 1password
      - npm
    state: present
  when: ansible_distribution_major_version|int >= 10

- name: Debian >=11 - Install packages
  ansible.builtin.apt:
    pkg:
      - python3-cairo  # required to fix default python
    state: present
  when: ansible_distribution_major_version|int >= 11
