---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    # https://www.freedesktop.org/software/systemd/man/sd_booted.html
    - name: All - Check if systemd is running
      ansible.builtin.stat:
        path: /run/systemd/system/
      register: stat_run_systemd

    - name: Flatpaks
      tags: [user]
      ansible.builtin.import_tasks: tasks/user/flatpaks.yml
  handlers:
    - name: systemctl --user daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user
      when:
        - stat_run_systemd.stat.exists
        - stat_run_systemd.stat.isdir
