---
- name: Playbook to install google cloud tools
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: GCloud
      tags: [system]
      become: true
      ansible.builtin.import_tasks: tasks/system_gcloud.yml
