---
- name: Playbook to install razer tools
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    signing_keys:
      razer_fedora:
        fingerprint: E96C496E4E77C159C2FCA053062F9FD4D6D11CE4
  tasks:
    - name: Razer
      tags: [system]
      become: true
      ansible.builtin.import_tasks: tasks/system/razer.yml
