---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    dive_version: 0.10.0
    signing_keys:
      epel:  # https://getfedora.org/security/
        "8":
          key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
          fingerprint: 94E279EB8D8F25B21810ADF121EA45AB2F86D6A1
        "9":
          key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
          fingerprint: FF8AD1344597106ECE813B918A3872BF3228467C
      rpmfusion_free_el:  # https://rpmfusion.org/keys
        "8":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-8
          fingerprint: 837935CD19E123AA7F8A8E69979F0C69158B3811
        "9":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-9
          fingerprint: EDC00FE7418C9DF7EF4991A47403EA33296458F3
      rpmfusion_nonfree_el:  # https://rpmfusion.org/keys
        "8":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-8
          fingerprint: CF9FD59F61D6612146CDAC8E14B6792DBDDA8475
        "9":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-9
          fingerprint: BB24128A4BB3C3352C0B75A2E4174E6BAAB212EA
      rpmfusion_free_fedora:  # https://rpmfusion.org/keys
        "28":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-28
          fingerprint: 34249D2CB3758B5548E2874FC08D326909EAB3F2
        "29":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-29
          fingerprint: BD127385C312090FF2F35FA11191A7C442F19ED0
        "30":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-30
          fingerprint: 80C3B2C6E727F3E092B473E03DF2CE43C0AEDA6E
        "31":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-31
          fingerprint: 59A7FE07F664C1B27687C5D26DEEF051C481937A
        "32":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-32
          fingerprint: 7BDA98EF593050A34B1697ABA0EE9D83100BCD92
        # Starting with 33 they keys are symlinked to a yearly signing key
        "33":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
          fingerprint: E9A491A3DE247814E7E067EAE06F8ECDD651FF2E
        "34":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
          fingerprint: E9A491A3DE247814E7E067EAE06F8ECDD651FF2E
        "35":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
          fingerprint: E9A491A3DE247814E7E067EAE06F8ECDD651FF2E
        "36":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
          fingerprint: E9A491A3DE247814E7E067EAE06F8ECDD651FF2E
        "37":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
          fingerprint: E9A491A3DE247814E7E067EAE06F8ECDD651FF2E
      rpmfusion_nonfree_fedora:  # https://rpmfusion.org/keys
        "28":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-28
          fingerprint: 3DE8C682E38EE9BC0FDFEA47FCAE2EA87F858107
        "29":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-29
          fingerprint: 18A50439A072A393E47178D49C009EABD6841AF8
        "30":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-30
          fingerprint: 80171C8D2CC8AAB84C8448E9BDD6ECC41D14A795
        "31":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-31
          fingerprint: 4CAB951A7493D92CADEC04219CE63A0354A86092
        "32":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-32
          fingerprint: FE5A9393CB6E271B5A90CC1B0D9A76996DC1BE18
        # Starting with 33 they keys are symlinked to a yearly signing key
        "33":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
          fingerprint: 79BDB88F9BBF73910FD4095B6A2AF96194843C65
        "34":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
          fingerprint: 79BDB88F9BBF73910FD4095B6A2AF96194843C65
        "35":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
          fingerprint: 79BDB88F9BBF73910FD4095B6A2AF96194843C65
        "36":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
          fingerprint: 79BDB88F9BBF73910FD4095B6A2AF96194843C65
        "37":
          key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
          fingerprint: 79BDB88F9BBF73910FD4095B6A2AF96194843C65
  tasks:
    - name: debug info
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
      tags: [never, debug]
    - name: debug info - ansible_architecture
      ansible.builtin.debug:
        var: ansible_architecture
      tags: [never, debug]
    - name: debug info - ansible_distribution
      ansible.builtin.debug:
        var: ansible_distribution
      tags: [never, debug]
    - name: debug info - ansible_distribution_major_version
      ansible.builtin.debug:
        var: ansible_distribution_major_version
      tags: [never, debug]

    # https://www.freedesktop.org/software/systemd/man/sd_booted.html
    - name: All - Check if systemd is running
      tags: [system, user, systemd]
      ansible.builtin.stat:
        path: /run/systemd/system/
      register: stat_run_systemd

    # Not all packages can be installed in WSL
    - name: All - Check if running in WSL
      ansible.builtin.set_fact:
        running_in_wsl: "{{ ansible_kernel.endswith('-WSL') or ansible_kernel.endswith('-WSL2') }}"

    ### --- System ---
    - name: Repositories
      tags: [system, dev, repo]
      become: true
      ansible.builtin.import_tasks: tasks/system/repositories.yml

    - name: Packages
      tags: [system, dev, packages]
      become: true
      ansible.builtin.import_tasks: tasks/system/packages.yml

    - name: Security Settings
      tags: [system, security]
      become: true
      ansible.builtin.import_tasks: tasks/system/security.yml

    ### --- Userspace ---
    # Install dotfiles first so CI can detect drift
    - name: User dotfiles
      ansible.builtin.import_tasks: tasks/user/dotfiles.yml
      tags: [user, dotfiles]
    - name: User applications
      ansible.builtin.import_tasks: tasks/user/applications.yml
      tags: [user, applications]
    - name: User autostart
      ansible.builtin.import_tasks: tasks/user/autostart.yml
      tags: [user, autostart]
    - name: User python
      ansible.builtin.import_tasks: tasks/user/python.yml
      tags: [user, python]
    - name: User rust
      ansible.builtin.import_tasks: tasks/user/rust.yml
      tags: [user, rust]
    - name: User UI
      ansible.builtin.import_tasks: tasks/user/ui.yml
      tags: [user, ui]
    - name: User ides
      ansible.builtin.import_tasks: tasks/user/ides.yml
      tags: [user, ides]
    - name: User bins
      ansible.builtin.import_tasks: tasks/user/bins.yml
      tags: [user, bins]
    - name: User systemd
      ansible.builtin.import_tasks: tasks/user/systemd.yml
      tags: [user, systemd]
      when:
        - stat_run_systemd.stat.exists
        - stat_run_systemd.stat.isdir
