---
- name: Centos - Install docker
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - libcrypt.so.1()(64bit)  # needed by docker-compose
