---
- name: CentOS - Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  retries: 5
  delay: 5
  loop:
    - code
    - dbus-daemon
    - kubectl
    - podman
    - python39-psutil
