---
# These need to be installed at the same time to avoid version conflicts
- name: CentOS - Install docker packages # noqa 403
  dnf:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: latest
