---
- name: CentOS - Check for Hashicorp support
  ansible.builtin.uri:
    url: "https://rpm.releases.hashicorp.com/RHEL/\
          {{ ansible_distribution_major_version | int }}/\
          {{ ansible_architecture }}/stable/repodata/repomd.xml"
  register: uri_hashicorp_repo_metadata
  ignore_errors: true

# https://www.hashicorp.com/security
- name: CentOS - Import Hashicorp signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg
    fingerprint: E8A032E094D8EB4EA189D270DA418C88A3219F7B
  register: rpm_key_hashicorp

- name: CentOS - Add Hashicorp repository
  ansible.builtin.yum_repository:
    file: hashicorp
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    enabled: "{{ uri_hashicorp_repo_metadata is succeeded }}"
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg

# TODO: remove this workaround when dnf uses the rpm key database
- name: RedHat - refresh dnf keys for Hashicorp  # noqa no-handler
  ansible.builtin.command: "dnf -q makecache -y --disablerepo='*' --enablerepo='hashicorp'"
  when: rpm_key_hashicorp.changed

- name: CentOS - rpm keys for Google
  ansible.builtin.import_tasks: ../rpm_keys_google.yml

- name: CentOS - Import kubernetes repository key - 1
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml.key
    fingerprint: 7F92E05B31093BEF5A3C2D38FEEA9169307EA071
  register: import_kubernetes_repository_key1

- name: CentOS - Import kubernetes repository key - 2
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml.key
    fingerprint: 59FE0256827269DC81578F928B57C5C2836F4BEB
  register: import_kubernetes_repository_key2

- name: CentOS - Add Kubernetes repository
  ansible.builtin.yum_repository:
    file: kubernetes
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      # Repository metadata keys
      - https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64/repodata/repomd.xml.key
      # Old repository metadata key
      # - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      # Package key
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  register: kubernetes_repository

# TODO: remove this workaround when dnf uses the rpm key database
- name: CentOS - refresh dnf keys for kubernetes  # noqa no-handler
  ansible.builtin.command: "dnf -q makecache -y --disablerepo='*' --enablerepo='kubernetes'"
  when: >
    kubernetes_repository.changed
    or import_kubernetes_repository_key1.changed
    or import_kubernetes_repository_key2.changed
    or import_glcoud_package_key.changed

- name: CentOS - Import RPM-GPG-KEY-rpmfusion-free signing key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_free_el[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.rpmfusion_free_el[ansible_distribution_major_version].fingerprint }}"
  when: ansible_distribution_major_version in signing_keys.rpmfusion_free_el

- name: CentOS - Add RPMFusion-free repository
  ansible.builtin.dnf:
    name:
      - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-\
        {{ ansible_distribution_major_version | int }}.noarch.rpm"
    state: present
  when:
    - ansible_distribution_major_version in signing_keys.rpmfusion_free_el
    - (not rpmfusion_free_repo.stat.exists) or (not rpmfusion_free_updates_repo.stat.exists)
  register: rpmfusion_free_install
  until: rpmfusion_free_install is succeeded
  retries: 5
  delay: 5

- name: CentOS - Import RPM-GPG-KEY-rpmfusion-nonfree signing key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_nonfree_el[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.rpmfusion_nonfree_el[ansible_distribution_major_version].fingerprint }}"
  when: ansible_distribution_major_version in signing_keys.rpmfusion_nonfree_el

- name: CentOS - Add RPMFusion-nonfree repository
  ansible.builtin.dnf:
    name:
      - "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-\
        {{ ansible_distribution_major_version | int }}.noarch.rpm"
    state: present
  when:
    - ansible_distribution_major_version in signing_keys.rpmfusion_nonfree_el
    - (not rpmfusion_nonfree_repo.stat.exists) or (not rpmfusion_nonfree_updates_repo.stat.exists)
  register: rpmfusion_nonfree_install
  until: rpmfusion_nonfree_install is succeeded
  retries: 5
  delay: 5

- name: CentOS - Install zoom updater dependencies - curl
  ansible.builtin.dnf:
    name:
      - curl
    state: present
    allowerasing: true  # curl-minimal may already be installed

- name: CentOS - Install zoom updater dependencies
  ansible.builtin.dnf:
    name:
      - make
      - coreutils-single  # provides basename
      - createrepo_c
      - rpm
    state: present

- name: CentOS - install zoom updater service
  community.general.make:
    chdir: /opt/zoom-yum-repo
    target: install-service
  when:
    - stat_run_systemd.stat.exists
    - stat_run_systemd.stat.isdir

- name: CentOS - start zoom updater service
  community.general.make:
    chdir: /opt/zoom-yum-repo
    target: start-service
  when:
    - stat_run_systemd.stat.exists
    - stat_run_systemd.stat.isdir

### Version specific repositories
