---
- name: CentOS - Import RPM-GPG-KEY-EPEL
  rpm_key:
    state: present
    key: "{{ signing_keys.epel[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.epel[ansible_distribution_major_version].fingerprint }}"

- name: CentOS - Import RPM-GPG-KEY-rpmfusion-free
  rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_free_el[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.rpmfusion_free_el[ansible_distribution_major_version].fingerprint }}"

- name: CentOS - Import RPM-GPG-KEY-rpmfusion-nonfree
  rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_nonfree_el[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.rpmfusion_nonfree_el[ansible_distribution_major_version].fingerprint }}"

- name: CentOS - Install EPEL repository
  dnf:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present

- name: CentOS - Add PowerTools repository
  yum_repository:
    file: CentOS-PowerTools
    name: PowerTools
    description: CentOS-$releasever - PowerTools
    mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=PowerTools&infra=$infra
    # baseurl: http://mirror.centos.org/$contentdir/$releasever/PowerTools/$basearch/os/
    gpgcheck: yes
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

- name: CentOS - Add RPMFusion-free repository
  dnf:
    name:
      - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present
  when: (not rpmfusion_free_repo.stat.exists) or
        (not rpmfusion_free_updates_repo.stat.exists)
  register: rpmfusion_free_install
  until: rpmfusion_free_install is succeeded
  retries: 5
  delay: 5

- name: CentOS - Add RPMFusion-nonfree repository
  dnf:
    name:
      - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present
  when: (not rpmfusion_nonfree_repo.stat.exists) or
        (not rpmfusion_nonfree_updates_repo.stat.exists)
  register: rpmfusion_nonfree_install
  until: rpmfusion_nonfree_install is succeeded
  retries: 5
  delay: 5
