---
# https://www.hashicorp.com/security
- name: CentOS - Import Hashicorp signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg
    fingerprint: E8A032E094D8EB4EA189D270DA418C88A3219F7B

- name: CentOS - Add Hashicorp repository
  ansible.builtin.yum_repository:
    file: hashicorp
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: CentOS - Import RPM-GPG-KEY-rpmfusion-free signing key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_free_el[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.rpmfusion_free_el[ansible_distribution_major_version].fingerprint }}"
  when: ansible_distribution_major_version in signing_keys.rpmfusion_free_el

- name: CentOS - Add RPMFusion-free repository
  ansible.builtin.dnf:
    name:
      - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present
  when:
    - ansible_distribution_major_version in signing_keys.rpmfusion_free_el
    - (not rpmfusion_free_repo.stat.exists) or (not rpmfusion_free_updates_repo.stat.exists)
  register: rpmfusion_free_install
  until: rpmfusion_free_install is succeeded
  retries: 5
  delay: 5

- name: CentOS - Import RPM-GPG-KEY-rpmfusion-nonfree signing key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ signing_keys.rpmfusion_nonfree_el[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.rpmfusion_nonfree_el[ansible_distribution_major_version].fingerprint }}"
  when: ansible_distribution_major_version in signing_keys.rpmfusion_nonfree_el

- name: CentOS - Add RPMFusion-nonfree repository
  ansible.builtin.dnf:
    name:
      - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm
    state: present
  when:
    - ansible_distribution_major_version in signing_keys.rpmfusion_nonfree_el
    - (not rpmfusion_nonfree_repo.stat.exists) or (not rpmfusion_nonfree_updates_repo.stat.exists)
  register: rpmfusion_nonfree_install
  until: rpmfusion_nonfree_install is succeeded
  retries: 5
  delay: 5
